version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo Entered the install phase...
    finally:
      - echo This always runs even if the update or install command fails 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
    finally:
      - echo This always runs even if the login command fails 
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - curl www.google.com >google1
      - chmod 755 google1
      - ls -la
      - codebuild-breakpoint
      - if [  -f ~/google1 ]; then tar -czvf google1.tar.gz ~/google1; else echo "no filename exists; fi
      - ls -la
      - aws s3 ls
      #- aws s3 cp google1 s3://s3nabintest1/Build1/
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - echo $CODEBUILD_SRC_DIR
      #- codebuild-breakpoint
artifacts:
  files:
    - '**/*'
  name: myname1

